<div>
    <label for="nickname">Enter nickname</label>
    <input type="text" id="nickname" name="user[nickname]" value="<?= htmlspecialchars($user['nickname'] ?? '') ?>" placeholder="asd1xx">
    <?php if (isset($errors['nickname'])): ?>
        <div><?= $errors['nickname'] ?></div>
    <?php endif ?>
</div>
<div>
    <label for="email">Enter email</label>
    <input type="text" id="email" name="user[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>" placeholder="asd1xx@mail.ru" required>
    <?php if (isset($errors['email'])): ?>
        <div><?= $errors['email'] ?></div>
    <?php endif ?>
</div>
