<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" required>
  <input type="submit" value="Search">
</form>
<table>
  <?php foreach ($users as $user): ?>
    <tr>
      <td>
          <?= $user['id'] ?>
      </td>
      <td>
          <?= $user['nickname'] ?>
      </td>
      <td>
          <?= $user['email'] ?>
      </td>
    </tr>
  <?php endforeach ?>
</table>