<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" required>
  <input type="submit" value="Search">
</form>
<table>
  <?php foreach ($users as $user): ?>
    <tr>
      <td>
          <?= htmlspecialchars($user['id']) ?>
      </td>
      <td>
          <?= htmlspecialchars($user['nickname']) ?>
      </td>
      <td>
          <?= htmlspecialchars($user['email']) ?>
      </td>
    </tr>
  <?php endforeach ?>
</table>
