<h1>New User</h1>
<hr>
<form action="/users" method="post">
  <div>
    <label for="nickname">Ваш nickname</label>
    <input type="text" id="nickname" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>" placeholder="asd1xx" required>
  </div>
  <div>
    <label for="email">Ваш email</label>
    <input type="text" id="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>" placeholder="asd1xx@mail.ru" required>
  </div>
  <div>
    <input type="submit" value="Submit" />
  </div>
</form>